version: "3.7"

services:
  # База данных
  db:
    container_name: db_name
    image: postgres:13.0-alpine
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env

  # Приложение
  app:
    build:
      context: .
    env_file:
      - .env
    command: ["/fastapi_app/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db